export const NOTIFICATIONS = {
  CONNECT_WALLET_L1: 'CONNECT_WALLET_L1',
  CONNECT_WALLET_L2: 'CONNECT_WALLET_L2',
  DEPOSIT_L1: 'DEPOSIT_L1',
  DEPOSIT_L2: 'DEPOSIT_L2',
  WITHDRAWAL_L1: 'WITHDRAWAL_L1',
  WITHDRAWAL_L2: 'WITHDRAWAL_L2'
}
